name: imposter
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.10
  device_info_plus: ^10.0.1
  firebase_core: ^2.27.2
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/mascot.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/img/mascot.png
  fonts:
    - family: Grandstander
      fonts: 
      - asset: assets/fonts/Grandstander-ExtraBold.ttf
    - family: ShortStack
      fonts:
      - asset: assets/fonts/ShortStack-Regular.ttf
    - family: ShadowsIntoLight
      fonts:
      - asset: assets/fonts/ShadowsIntoLight-Regular.ttf
    - family: TiltNeon
      fonts:
      - asset: assets/fonts/TiltNeon.ttf